title: Skycrazyk 
author:
  name: Dmitry Karyakin
  email: skycrazyk@gmail.com
description: There is no spoon ðŸ¥„
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized 
  nav_pages:
    - about.md
    - portfolio.md